### ISSUE TITLE
Hi! Outstanding work. A few questions.

### ISSUE THREAD

**Issue by harold** [Azel4231/dsui#1]
Hello, nice work here, was thinking along these lines again today and found this project.

What's the status? Are you using this? Have you moved on to something else? This type of tool is sorely needed all the time - I have fond (but vague) memories of FRED, Clozure common lisp, and their inspector.

I ran your code on some of my data today:

![image](https://user-images.githubusercontent.com/7443/67030922-b0ff6400-f0cd-11e9-9965-89298ed6b05b.png)

The tabs on the left could perhaps be improved by being ordered, and it seems like (at least on this data) putting one map key/value per line may be more clear than sometimes word-wrapping them.

I guess my question is, should we be working on this library? Or should we mix our efforts elsewhere?

Again, neat work here. Appreciated!

**Comment by Azel4231** [comment]
Hi Harold, thanks a lot!

I am using this in every other spare-time projects of mine. 
Consider this as "actively maintained" (in the sense of "does not need maintenance"). Sorting the tabs is a good idea, which I might add sometime. Other than that there is not a whole lot I would want to add feature-wise. 

Your data looks a lot more "listy" than mine. I now see why the tab presentation is sub-optimal for your data. You might also want to look at:
* [inspect-tree](https://clojuredocs.org/clojure.inspector/inspect-tree) which is better for listy data
* and [Cognitect's REBL](http://rebl.cognitect.com/download.html) which is a lot more general and also extensible in its data-presentation

So should you be working on this? I don't know really. dsui is really a hobby project and there are more powerful and more general tools out there. But then again it's really small (sub 200loc), so might as well maintain your own fork.

HTH Cheers!

**Comment by harold** [comment]
I appreciate your reply.

I am familiar with `clojure.inspector` and REBL - both leave something to be desired.

I'm glad to know you're here, and forking is a great idea. Not sure if I'll dive in here, or maybe mix my efforts with the Cider inspector.

Regardless, take care, and thanks again for sharing this code.
